# Generated by Django 5.2.8 on 2025-12-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_author_post_content_post_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='This is some the title', max_length=250),
        ),
    ]
